### ISSUE TITLE
DeserializeOwned

### ISSUE THREAD

**Issue by dtolnay** [paulkernfeld/ndarray-csv#1]
https://github.com/paulkernfeld/ndarray-csv/blob/a69bdf9320da2d669dcc39bf813581863c6f4a10/src/lib.rs#L79-L83

---

The `for<'de> Deserialize<'de>` bound is more readably written using [`DeserializeOwned`](https://docs.serde.rs/serde/de/trait.DeserializeOwned.html).

```rust
where
    A: Copy + DeserializeOwned,
```

**Comment by paulkernfeld** [comment]
Thanks for the tip! Done.
