### ISSUE TITLE
Matching pandas behavior: Indexed write and / or writing differing length arrays as one "DataFrame"?

### ISSUE THREAD

**Issue by dam5h** [paulkernfeld/ndarray-csv#11]
I needed to match a pandas (python library) based output which had integer indexes in the far left column of the written csv.  This was trivial to implement by extending your trait and is very little code.  

Separately, I also needed to write a "dataframe" in Pandas style that contained different column lengths (which ended up needing to be a Vec of arrays in ndarray) which Pandas would just write with empty cells of the "shorter" columns.  If you think either of these features would be useful I will open a PR, just let me know.   Best, Dave

**Comment by paulkernfeld** [comment]
Thanks for the suggestion! I'd like to keep this crate specific to CSV, but maybe it could make sense to add this to ndarray or even [rust-numpy](https://github.com/PyO3/rust-numpy).

**Comment by dam5h** [comment]
Ah, yeah, totally get it!  Just to clarify, its still CSV data, just has a leading integer for the "index" in each row.  Honestly I don't think it's very useful either, but I had to conform my output to match what pandas was outputing via its `to_csv` method.  Something like this:

```
0, 1.5465, 4.54658
1, 5.654, 8.4888
2, 3.41, 9.4689
```

For the other pandas related DataFrame csv output I mentioned, the output would be:

```
0, 1.5465, 4.54658
1, 1.5465, 4.54658
2, , 8.4888
3, , 9.4689
```
The missing values are because that column of the frame isn't as long as the second column.

Again, I don't think these are all that useful generally, just wanted to clarify what I was suggesting from having to match some existing pandas output with my rust program.

**Comment by paulkernfeld** [comment]
Ah, sorry, I didn't understand correctly. I think a CSV structure like this might be a better fit for a crate with more data frame capabilities, which isn't really what ndarray gives us. For example, I bet a lot of users would want string headers.
