### ISSUE TITLE
Support for time series ? 

### ISSUE THREAD

**Issue by ghost** [paulkernfeld/ndarray-csv#14]
I was wondering if there was a way to load time series CSV natively from the current implementation of ndarray-csv ? I'm having a hard time loading 2D arrays with dates (as NaiveDate) in first column and values as f64 floats in the second column. 

What I'd like to achieve is to format directly the ndarray with different dtypes (as it would be possible to do in Python). So far, what I managed to do is to deserialize the csv using the csv and serde crates using the following code:

```
#[derive(Deserialize)]
struct Record {
    #[serde(deserialize_with = "naive_date_time_from_str")]
    date: NaiveDate,
    value: f64
}

fn naive_date_time_from_str<'de, D>(deserializer: D) -> Result<NaiveDate, D::Error>
where
    D: Deserializer<'de>,
{
    let s: String = Deserialize::deserialize(deserializer)?;
    NaiveDate::parse_from_str(&s, "%Y-%m-%d").map_err(de::Error::custom)
}
```

And my current main function would be as follow:

```
fn main() -> Result<(), Box<dyn Error>> {
    let mut reader = ReaderBuilder::new()
        .has_headers(true)
        .delimiter(b',')
        .from_path("./data/time_series.csv")?;

    for record in reader.deserialize::<Record>() {
        let record: Record = record?;
        println!(
            "date {}, value = {}",
            record.date.format("%Y-%m-%d").to_string(),
            record.value
        );
    }

    let data: Array2<String> = reader.deserialize_array2_dynamic()?;

    Ok(())
}
```

I'm also considering creating two splitted ndarrays. That would be the way to go in order to move on. But I think it might be a cool feature to call the deserialize_array2 function(s) with a struct / record as argument.

Is ndarray able to handle multiples types of data in a Array2 ? Am I missing something important ? Would my request be possibly implemented in ndarray-csv ?

**Comment by paulkernfeld** [comment]
Unfortunately, an ndarray holds data of a uniform type, so it doesn't handle this use case where different columns have different types. I'd suggest trying out a data frame (the equivalent of Python's pandas) instead.

**Comment by ghost** [comment]
Thnaks for your feedback. I'll close the issue
