### ISSUE TITLE
Serialization silently fails if the array is in non-standard memory layout

### ISSUE THREAD

**Issue by alexander-novo** [paulkernfeld/ndarray-csv#15]
Serialization silently fails if the array is in non-standard memory layout (such as via transposition).

Consider this example, which reads an array from a csv file, transposes it, and attempts to write it back:

```Rust
    let data: Result<Array2<f32>> = try {
        csv::ReaderBuilder::new()
            .from_path(&in_path)?
            .deserialize_array2_dynamic::<f32>()?
    };

    let data =
        data.unwrap_or_else(|e| panic!("Couldn't read data from `{}`:\n{e}", in_path.display()));

    let data = data.t().into_owned();

    let result: Result<()> = try {
        csv::WriterBuilder::new()
            .from_path(&out_path)?
            .serialize_array2(&data)?
    };

    result.unwrap_or_else(|e| panic!("Couldn't write data to `{}`:\n{e}", out_path.display()));
```

This code will silently fail, and the resulting csv file will have nothing but empty quotation marks for each row of the input array. This is because the `serialize_array2` method uses `ndarray::ArrayBase::as_slice()`:

https://github.com/paulkernfeld/ndarray-csv/blob/3f7deef7955d983ce4855722d48aec40cfcf927d/src/lib.rs#L179

but the `as_slice` method [can fail](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.as_slice) and return `None` if the elements aren't contiguous or in standard layout. This is serialized as a blank row, when it should be an error (or perhaps even automatically fixed via [`ndarray::ArrayBase::as_standard_layout()`](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.as_standard_layout)).

**Comment by paulkernfeld** [comment]
Thanks for catching this! I agree that this is a bug. It seems friendlier to automatically fix this, and I think it should be efficient enough not to stress about.
