### ISSUE TITLE
Do not mix type parameters and impl Trait

### ISSUE THREAD

**Issue by dtolnay** [paulkernfeld/ndarray-csv#2]
https://github.com/paulkernfeld/ndarray-csv/blob/a69bdf9320da2d669dcc39bf813581863c6f4a10/src/lib.rs#L79-L83

---

Mixing type parameters and impl Trait in the same signature makes it impossible to use with turbofish. Turbofish is commonly needed for signatures where some type parameter appears only in the return type.

```rust
use std::io::{Cursor, Read};

fn read<A>(_reader: impl Read) -> A {
    unimplemented!()
}

fn main() {
    let reader = Cursor::new(Vec::new());
    let _: u8 = read(reader); // okay

    let _ = read::<u8>(reader); // not supported
}
```

**Comment by paulkernfeld** [comment]
This makes sense. Would you recommend switching to all `impl Trait` or all type parameters?

**Comment by paulkernfeld** [comment]
As a more general note, is there ever a situation where it might be worth it to mix type parameters and `impl Trait` even though it makes it impossible to use the turbofish operator?

**Comment by dtolnay** [comment]
You wouldn't be able to express the signature of `read` with all impl Trait because `A` appears in the return type.

Using all type parameters can be annoying when you need to turbofish one of the type parameters but not the other. For example if you had `fn read<R, A>` then the caller would need to write `ndarray_csv::read::<_, u8>` to specify `A` but infer `R`.

You could consider either a trait object (to avoid having an `R` type parameter entirely) or an extension trait method (which places `R` on the impl and `A` on the method, allowing turbofish for one or both independently). An extension trait could work much like the [`csv::Reader::deserialize`](https://docs.rs/csv/1.0/csv/struct.Reader.html#method.deserialize) method: `reader.read_array::<u8>(2, 3)`.

> As a more general note, is there ever a situation where it might be worth it to mix type parameters and `impl Trait` even though it makes it impossible to use the turbofish operator?

Turbofish is typically not needed for signatures where type parameters appear only in the argument types, so mixing is not problematic for those. Turbofish is mostly for methods with a type parameter in the return type such as [`Iterator::collect`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect), [`str::parse`](https://doc.rust-lang.org/std/primitive.str.html#method.parse), [`serde_json::from_str`](https://docs.serde.rs/serde_json/fn.from_str.html).

**Comment by paulkernfeld** [comment]
Hmm, this issue is a bit deeper than I had realized. I like your extension trait suggestion!

Is there somewhere that I could go to read more about how to choose generics in Rust?

**Comment by paulkernfeld** [comment]
Okay, I have now implemented the extension trait suggestion. I think I did it correctly, but please let me know if I have gotten something wrong.
