### ISSUE TITLE
Consider removing failure::Error from public API

### ISSUE THREAD

**Issue by dtolnay** [paulkernfeld/ndarray-csv#3]
Registering the discussion in https://www.reddit.com/r/rust/comments/9nu6o0/reflections_on_implementing_the_ndarraycsv_crate/e7p1l7t/. `failure::Error` is convenient for use at the application level but causes problems when produced by a library.

**Comment by paulkernfeld** [comment]
I just asked this in the Reddit thread, but I'm curious to hear what problems you're thinking of in this case. It doesn't seem like too much of a burden for end users to call `compat`, but I'm probably missing some deeper issues at play.

**Comment by paulkernfeld** [comment]
I found the responses in the Reddit thread compelling, so I have removed `failure`.
