### ISSUE TITLE
`ReadError` should implement `std::error::Error`

### ISSUE THREAD

**Issue by lbolla** [paulkernfeld/ndarray-csv#4]
Title says it all. It seems logical for an error to implement `std::error::Error`.
I've seen https://github.com/paulkernfeld/ndarray-csv/issues/3.

Also, implementing `From` seems useful (e.g. https://doc.rust-lang.org/book/first-edition/error-handling.html#error-handling-with-a-custom-type) so that the `main` function in the README (https://github.com/paulkernfeld/ndarray-csv/blob/master/README.md) can return `Result<(), Error>` and use `try!` instead of `expect()` calls.

**Comment by paulkernfeld** [comment]
Thanks for pointing this out! I have now implemented `Error` for `ReadError`.

I'm not sure that I understand your suggestion about `From`: if I implement `From<T>` for `ReadError`, what type should I put for `T`?

Also, you may have already seen this, but [the `?` operator can now be used in place of the `try!` macro](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html).

**Comment by lbolla** [comment]
I am aware that `?` is just syntactic sugar over `try!`.
Regarding `From`, I was suggesting to implement something like: https://docs.rs/csv/1.0.2/src/csv/error.rs.html#105-107
which allows to convert `ReadError`s to `std::io::Error`, or some other std error, so that they can be used easily in `fn main()` functions. Just a suggestion: I don't know if it makes sense for your library, really.

**Comment by lbolla** [comment]
Btw, there are crates (e.g. https://jeltef.github.io/derive_more/derive_more/from.html) that automate deriving `From` for trivial types.

**Comment by paulkernfeld** [comment]
I like your suggestion of removing the `expect` calls from the doctest, but I decided to take another strategy to implement it: I changed the signature of the `main` function to return `Result<(), Box<Error>>`.
