### ISSUE TITLE
Replace `panic!` with `Error`

### ISSUE THREAD

**Issue by lbolla** [paulkernfeld/ndarray-csv#5]
I don't quite understand why it's `panic!`ing here:
https://github.com/paulkernfeld/ndarray-csv/blob/c3ee28abd5d04715164c602ddb044a174b391a18/src/lib.rs#L106

Could it not return an error, instead?

**Comment by paulkernfeld** [comment]
This was a situation that was "impossible," i.e. indicating a programming error on my part, so a `panic!` was the right choice. I've now rewritten this section to be a bit more elegant and removed the `panic!`.
